### ISSUE TITLE
URL-encoding credentials not working

### ISSUE THREAD

**Issue by woytam** [friends-of-reactphp/mysql#100]
Hello, I have problems with `rawurlencode` credentials as mentioned in #98. I have tested it with `pass+` urlencoded as `pass%2B`.
In [`Factory/createConnection($uri)`](https://github.com/friends-of-reactphp/mysql/blob/db9466bc118e1320eee22bf747047967c806885e/src/Factory.php#L145) there is calling to `parse_url` function to get components of URL. 'pass' component is passed in parameter to [`AuthenticateCommand`](https://github.com/friends-of-reactphp/mysql/blob/db9466bc118e1320eee22bf747047967c806885e/src/Commands/AuthenticateCommand.php).
[`AuthenticateCommand\getAuthToken()`](https://github.com/friends-of-reactphp/mysql/blob/db9466bc118e1320eee22bf747047967c806885e/src/Commands/AuthenticateCommand.php#L55) use this password to make `sha1` of the password, but I cannot find `rawurldecode` function somewhere. And because sha1 of `pass+` and `pass%2B` is different, the urlencoded password failed (if used some non standard characters in it).

__System Info__
Apache 2.4.20 on Windows 7 x64
MariaDB 10.2
PHP 7.1.10
react/mysql: v0.5.2

**Comment by clue** [comment]
@woytam Thanks for reporting! I can reproduce the problem you're seeing and I'm preparing a fix for this asap.
