### ISSUE TITLE
Fatal error:  Allowed memory size

### ISSUE THREAD

**Issue by Spartaques** [friends-of-reactphp/mysql#104]
`require 'vendor/autoload.php';

$loop = \React\EventLoop\Factory::create();
$factory = new Factory($loop);

$uri = 'root:@localhost/CCLOAN_ES_PROD_LOCAL';
$connection = $factory->createLazyConnection($uri);

$connection->query('SELECT count(*) FROM holidays')->then(function (QueryResult $command) use ($connection){
    $queryCount = $command->resultRows[0]["count(*)"];
    print_r($queryCount);

    for($i=0; $i<$queryCount -1; $i++) {
            $connection->query('SELECT * FROM holidays LIMIT 1')->then(
                function (QueryResult $command) {
                    print_r($command->resultFields);
                    print_r($command->resultRows);
                    echo count($command->resultRows) . ' row(s) in set' . PHP_EOL;
                },
                function (Exception $error) {
                    print_r(debug_backtrace());
                }
            );

    }

});

$connection->quit();

$loop->run();
`

What i'm doing wrong that my memory leaks?

**Comment by clue** [comment]
@Spartaques Thanks for reporting, but I'm not entirely sure I follow what you're trying to achieve here.

Your first query will return the number of rows in your table, let's say this would be 100000. The next loop will then start one query per row, i.e. it will enqueue 100000 queries. This is bound to need a lot of memory just to keep track of the state for each query, but this should never *leak* any memory. Note that unlike a synchronous counterpart with traditional PDO, this will not execute this one after another, but will actually queue all commands at the same time, thus taking a lot of memory.

As an alternative, you may want to limit the number of queries you send concurrently, for example by using https://github.com/clue/reactphp-mq or completely reconsidering how your application is supposed to work, for example by trying to write this to only execute a single SQL statement which returns a (possibly large) result set.

I hope this helps :+1:
