### ISSUE TITLE
multiple insert support

### ISSUE THREAD

**Issue by blacktek** [friends-of-reactphp/mysql#114]
Hello,
 it would be great to support multiple insert statements by accepting an array of array as parameter of the query method (like PDO)
Possible?

moreover how to access the database link in order to issue mysqli_real_escape_string($link, ...)? it's needed until the multiple insert is supported in order to escape strings passed to mysql

**Comment by clue** [comment]
@blacktek Thanks for this interesting question.

Support for extended insert statements is handled by the database side, i.e. it it already supported by this library when constructing the right query like this:

```php
$db->query(
    'INSERT INTO users (name, email) VALUES (?, ?), (?, ?)'
    [
        $users[0]->name,
        $users[0]->email,
        $users[1]->name,
        $users[1]->email,
    ]
);
```

If you're handling a variable number of entries, you have to concatenate the right number of placeholders to the SQL statement accordingly. Note that depending on your database structure there's a sweet spot somewhere between a few hundred to few thousand rows per insert, so you may have to chunk very large inserts accordingly.

I hope this helps :+1:

**Comment by blacktek** [comment]
Hello,
 yesterday I tested that one, but seemed to not work; I've to check again.

Wouldn't be possible to add something like this too?

$db->query(
    'INSERT INTO users (name, email) VALUES ?'
    [
        $users[0]->name,
        $users[0]->email,
        $users[1]->name,
        $users[1]->email,
...
        $users[N]->name,
        $users[N]->email,
...
    ]

this is the syntax of sqlite too, basically the framework takes care to add () around each record. Possible?

Regarding the extra OT question: any way to call the mysqli_real_escape_string function with a valid db connection? in the library now I see that some escaping is done (but I think weaker than mysqi_real_escape_string and in any case it seems I'm not able to directly access the escape function)

Thank you! :)

**Comment by clue** [comment]
Give it a try and report back, it should work :+1: 

Automatic escaping of arrays can be problematic if input is not carefully sanitized (it's easy to forget that `$_GET['foo']` could be an array and would break the statement). I'm not sure if it's reasonable, but if anybody feels like filing a PR to see what implications this has, go for it :+1: 

This project implements the binary network protocol that is used by MySQL and as such does not rely on libmysql(nd). This also implies it can not expose any of its functions, such as `mysql_real_escape_string()` etc. The automatic escaping of placeholder variables should take of this without exposing this as a dedicated function. If you feel anything is missing or incomplete, please let us know and I'm happy to take a look :+1:

**Comment by blacktek** [comment]
Hi Christian, I remember: I nested arrays (like in my last example) and it didn't work for this reason. So my fault 100%, by putting ? ? ? ? and one simple flat array with the same amount of elements will work.

Regarding my request I think it makes sense. Of course mistakes can be made and in that case the query will throw an error; I wouldn't care too much about incorrect usage if people are aware of what they do. I think it's quite usefull. With reactphp I think one gain is to push elements in queues and make bulk inserts to avoid many queries, so this would be a quite usefull addition.

Regarding the escape why not changing the public function escape($str) in a static function? the "private $escapeChars = array(..." could become a class const array.

**Comment by clue** [comment]
@blacktek Happy to hear you've got this sorted out! If you feel your feature request makes sense, go for it, we very much welcome PRs and I'm happy to help review this :+1:

**Comment by blacktek** [comment]
@clue I've found a workaround (found before too), but at the end I was just asking if you could add the 2 new features asked in my previous ticket. possible?

**Comment by clue** [comment]
@blacktek This is an open-source project, so everybody's invited to contribute :+1:

(If you're asking for me personally to add your requested features, you can always drop me an email and we'll work out the details, I work as a freelance software engineer.)

**Comment by blacktek** [comment]
yeah, it was like a feature request, I don't need to have this implemented just for me, but thanks for the offer. And good to know that you work as a freelance software engineer ;)

**Comment by WyriHaximus** [comment]
@blacktek you can always implement the feature your self and PR it.
