### ISSUE TITLE
writable pipe destination

### ISSUE THREAD

**Issue by akeebismail** [friends-of-reactphp/mysql#118]
how do I implement pipe with writable stream resources?
it's stated in the docs but it was not clear enough .
```php
 $output = new WritableResourceStream(STDOUT, $loop); $output->on('data', function ($data){
       print 'data in pipe';
       print_r($data);
    }); 
  $factory->createConnection($url)->then(function (ConnectionInterface $connection) use ($output){
        $connection->queryStream('select * from sales_reports')->pipe($output);
    }, function (Exception $e){
    });
    $loop->run(); 
```

I want to read from one table, process it and write the results back to another table

**Comment by WyriHaximus** [comment]
Haven't used this package myself but my bet is that you want a `ThroughStream` in this case. Maybe @clue can shed a light on this?

**Comment by clue** [comment]
@akeebismail Excellent question!

You may want to take a look at https://github.com/clue/reactphp-flux, here's the gist:

```php
$transformer = new Clue\React\Flux\Transformer(1, function (array $data) use ($db) {
    return $db->query(
        'INSERT INTO table (name, email) VALUES (?, ?)',
        [$data['name'], $data['email']]
    );
});

$stream = $db->queryStream('SELECT name, email FROM table');
$stream->pipe($transformer);
```

This will throttle your input stream even if you're processing millions of records and only ever execute one `INSERT` after another. I've used this in the past without issues.

If you're processing a large number of records, you will probably want to use some form of extended batch inserts to get a significantly better throughput (buffer and insert `n` records in a single statement). I've also implemented this in the past, but I'm unable to share this here at the moment. If you're interested in this for a commercial project, consider sending me an email and we can work out something for you.

I hope this helps :+1:
