### ISSUE TITLE
Help required on  HappyEyeBallsConnectionBuilder error

### ISSUE THREAD

**Issue by satishtaluru** [friends-of-reactphp/mysql#119]
Hi,
  When  running  examples/01-query.php this file I am getting error as Argument 1 passed to React\Socket\HappyEyeBallsConnectionBuilder::React\Socket\{closure}() must be of the type array, null given, called in

**Comment by WyriHaximus** [comment]
Hey @satishtaluru, does the error also include a line?

**Comment by satishtaluru** [comment]
Argument 1 passed to React\Socket\HappyEyeBallsConnectionBuilder::React\Socket\{closure}() must be of the type array, null given, called in /opt/lampp/htdocs/learning/m/vendor/react/promise/src/FulfilledPromise.php on line 25 and defined in /opt/lampp/htdocs/learning/m/vendor/react/socket/src/HappyEyeBallsConnectionBuilder.php on line 68

**Comment by clue** [comment]
@satishtaluru Thanks for reporting, this is indeed a bug in the underlying react/socket component that will only be shown when using legacy PHP 5.

I've just filed https://github.com/reactphp/socket/pull/230 to fix this underlying issue :+1: In the meantime, we highly recommend using the latest PHP version in which case this error will not be shown.
