### ISSUE TITLE
Simultaneous queries while streaming

### ISSUE THREAD

**Issue by pavarnos** [friends-of-reactphp/mysql#122]
Hi. I wanted to make a pull request to update the README.md, but was not sure of the correct wording. This is vaguely what I want to say. Is it correct?

for `queryStream()`- if you are streaming eg thousands of rows and then want to make other database calls using eg `query()` to update some of the rows you are reading, you cannot use the same database connection. You need to use a separate connection. Each connection is good for only one active query at a time.

**Comment by clue** [comment]
@pavarnos Thanks for reporting, I can see where you're coming from and agree it might make sense to be clearer about this specific use case.

The suggested wording sounds too limiting IMHO and is perhaps a bit imprecise. The MySQL protocol is inherently sequential, so if you try to send multiple async queries, it will actually start processing only the first one and will enqueue all others. The `queryStream()` is no exception to this rule, it just happens to be a command that often takes very long (especially when processing millions of rows).

If you run one query for every row you're reading from such a query stream, you're essentially enqueuing a lot of commands. This works just fine for a few hundred or thousands of commands, but eventually you're bound to run out of available memory.

You can avoid this situation by using multiple database connections or by making sure your streaming query doesn't emit "too many" rows.

You can also use https://github.com/clue/reactphp-mq to avoid queuing "too many" operations. For instance, this also allows you to abort excessive queries.

What do you think about this?

**Comment by pavarnos** [comment]
Thanks for the clarification. I think all that is needed is some comment similar to what you say above to let people know. It cost me a couple of days to figure this out. Would be nice to save that time for those who follow.

**Comment by clue** [comment]
> The MySQL protocol is inherently sequential, so that all commands will be performed in order and outstanding command will be put into a queue to be executed once the previous queries are completed.

PRs are very much appreciated if you feel there's something that's unclear or could be improved :+1: 

Other than that, I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can always reopen this :+1:
