### ISSUE TITLE
Parsing objects to QueryResult

### ISSUE THREAD

**Issue by KristienJones** [friends-of-reactphp/mysql#124]
Hi.
I'm using **Ratchet** for a basic websocket server.
I needed to use async MySQL so i've implemented this. I have one issue though, I'm using MySQL to authenticate connections to the websocket but I can't seem to **parse the connection object into the QueryResult function**. 

**My logic is as follows:**
User connects with authentication token, Then I check the token to the database, and if it's not authenticated then the connection closes. Simple right? Not really... it seems.

I do these checks in the **onOpen** function, and I need to call **$conn->close();** to close the connection if authentication fails. Here is my onOpen code:
```
public function onOpen(ConnectionInterface $conn) {
	$this->clients->attach($conn);
	echo "New connection! ({$conn->resourceId})\n";
	
	$connection = $this->factory->createLazyConnection($this->uri);
	$connection->query("select token from wsSessions where userID = ? limit 1",[1])->then(function(QueryResult $command) {
		//logic here, if not authorized, close connection
		//Need to access $conn->close(); here...
	});
	$connection->quit();
}
```

If anyone can help, I'd really appreciate it.
Thanks.

**Comment by yanmandev** [comment]
Use the set($conn) operator in the "then" callback function

**Comment by clue** [comment]
@KristienJones Welcome to @ReactPHP :wave: 

As @yanmandev already pointed out, you simply need to add a `use ($conn)` to your callable to be able to access this variable in your closure.

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can always reopen this :+1:
