### ISSUE TITLE
Ratchet Websocket best practice

### ISSUE THREAD

**Issue by manuduxi** [friends-of-reactphp/mysql#125]
Hey,

I've build a Websocket chat based on ratchet that uses reactphp async mysql and just got a couple of questions to make sure I'm doing things right, as I couldn't really find any examples out there.

So, the Socket will be used by different applications, each of them has it's own database where the data has to be stored and published, which means there are multiple Lazy connections created, this is done by the Ratchet Pusher.
**There is one database locally on the Websocket server that stores all connected interfaces in one table, out of there the connections are distributed.**

The push-server starts the event loop and passes the mysql factory to the pusher constructor (push-server.php):

My first question is: Is it ok like that to pass the whole factory object directly to the pusher?
<pre>
require dirname(__DIR__).'/websocket/vendor/autoload.php';

use React\MySQL\Factory;
use React\MySQL\QueryResult;

$loop = React\EventLoop\Factory::create();
$factory = new Factory($loop);
$pusher = new websocket01\Pusher($factory);

$webSock = new React\Socket\Server('0.0.0.0:8090', $loop);
$webServer = new Ratchet\Server\IoServer(
    new Ratchet\Http\HttpServer(
        new Ratchet\WebSocket\WsServer(
            new Ratchet\Wamp\WampServer(
                $pusher
            )
        )
    ),
    $webSock
);

$loop->run();
</pre>

The Pusher then creates a lazy connection for each connected Interface in the constructor, and thats my second question: Is it better to create just one async db connection at all and keep it alive (like now), or is is better to reopen the connection at every client interaction ?

(Pusher.php):
<pre>
    protected $connection;
    protected $subconnections = array();

    public function __construct($factory){
        //Main Websocket db
        $uri = 'localhost...';
        $this->connection = $factory->createLazyConnection($uri);

        //Create array with Connections to Sub dbs for every entry in the interface table
        $stream = $this->connection->queryStream('SELECT * from interfaces');

        $stream->on('data', function ($interface) use ($factory) {

                if (!array_key_exists($interface['interface_dbhost'], $this->subconnections)) {
                    $uri = "".$interface['interface_dbuser'].":".$interface['interface_dbpass']."@".$interface['interface_dbhost'].":".$interface['interface_dbport']."/".$interface['interface_dbname']."";

                    $this->subconnections[$interface['interface_dbhost']] = $factory->createLazyConnection($uri);
                }
        });
        $stream->on('end', function () {
            echo 'Completed.';
        });
    }
</pre>

The main (local) database will still be used to save clients data, errors, verify tokens etc.

The right database connection will then be chosen in onopen, onsubscribe, onpublish... automatically out of the subconnections array, depending on the application the client comes from, and the action he wants to perfom, for e.g:

<pre>
    public function onPublish(ConnectionInterface $conn, $conversation_id, $event, array $exclude, array $eligible) {
        $obj = json_decode($event);
        $interface = $obj->frontend;
        $channel = $obj->channel;

        $db = $this->selectDatabase($conversation_id, $interface); //Choose right database connection
        $clienthandler = new Clienthandler\Clienthandler($this->connection);

        $action = $this->processRequest($db,$obj, $conversation_id, $clienthandler, $operatorhandler, $channel);
    }
</pre>

I'm also passing the local db connection to the clienthandler too, as I need it there to log actions.

<pre>
    public function selectDatabase($conversation_id, $interface) {
            if(array_key_exists($interface, $this->subconnections)) {
                $dbconn = $this->subconnections[$interface];

                $dbconn->ping()->then(function () {
                    echo 'Connection alive' . PHP_EOL;
                }, function (Exception $e) {
                    echo 'Error: ' . $e->getMessage() . PHP_EOL;
                });
            }
        }
        return $dbconn;
    }
</pre>

The clienthandler then saves the data and broadcasts it to all subscribers

Actually this is working perfect for now, but as I mentioned above, I'm not sure if this is the best way to do this if there are 1000+ Users connected at the same time.

I'm open for any advice :-)

Thank you for your help

**Comment by WyriHaximus** [comment]
Ok so looking at your question I won't go with passing in the factory. But by wrapping the factory in a pool that will open a connection when no idle connection can be reused. Make sure that pool is using a pool per database to avoid accidentally running queries in the wrong database.

**Comment by WyriHaximus** [comment]
Why would you need a child process for every database?

**Comment by manuduxi** [comment]
"Make sure that pool is using a pool per database" -
because I can only find documentations about React child-proccess-pools, can you please point me into the right direction here?

**Comment by WyriHaximus** [comment]
Ow so like that. So have one pool object, that internally keeps a list of connections per host+database (a pool per database) and looks in that host+database pool for an idle connection when you need to run a query.

**Comment by manuduxi** [comment]
ok now I got it, thanks a lot!
