### ISSUE TITLE
If invalid user / password is provided, there is no error and timeout for time

### ISSUE THREAD

**Issue by carliedu** [friends-of-reactphp/mysql#128]
I forced an invalid user/password, but are not getting an message. The promise ends by timeout.

**Comment by clue** [comment]
@carliedu Thanks for reporting, but I can not reproduce this locally.

I've verified this to properly reject the promise right away. This is also covered by our test suite, so this is tested on a regular basis: https://github.com/friends-of-reactphp/mysql/blob/c6daf35a494817d50298a29c858e3290b6db0e88/tests/FactoryTest.php#L94-L112

Can you try running the test suite and detailed in the documentation to verify this works on your end? It this doesn't work, can you provide steps to reproduce this (packages versions, OS etc.)?

This doesn't look like an open issue in this project, so I'm closing this for now. Please feel free to come back with more details if this problem persists and we can reopen this :+1:

**Comment by carliedu** [comment]
Thanks @clue. I never used phpunit. I will look for it.

**Comment by carliedu** [comment]
I do not find the problem. As I has edited some Classes to find the error (first because connection refused), probably I made a mistake.
I begun a new project, and it works. 
Excuse me.
