### ISSUE TITLE
查询是否能确保串行

### ISSUE THREAD

**Issue by moonwith** [friends-of-reactphp/mysql#140]
The MySQL protocol is inherently sequential, so that all queries will be performed in order and outstanding queries will be put into a queue to be executed once the previous queries are completed.
请问下无论多复杂的查询，类似存储过程和事务都能确保串行的顺序吗？这个有没官方文档支持呢？

**Comment by WyriHaximus** [comment]
Hey @moonwith, could you translate the whole message to English? Not sure if translation for both non-English parts are correct.
