### ISSUE TITLE
Implementing laravel query builder

### ISSUE THREAD

**Issue by mahmutbayri** [friends-of-reactphp/mysql#153]
Do you think that using a query builder package is a good idea?

This is a prototype:

https://gist.github.com/mahmutbayri/4278c2b1c00c42f30b4c54af2c3a5d0a

If we support `illuminate/database` we can use its many benefits migration, seeder so on.

Thanks.

**Comment by mahmutbayri** [comment]
2nd prototype

https://gist.github.com/mahmutbayri/44e35fa110148665d6f11229ee83427d

**Comment by SimonFrings** [comment]
@mahmutbayri Thanks for opening this issue.

Looks like a cool idea, definitely something others can use too :+1: 
I would say if you get a benefit out of it it's always a good idea ^^

I don't know if this will be a part of the project any time soon, but if it fit your needs go for it!

**Comment by clue** [comment]
What @SimonFrings says! :+1: Thank you for sharing, I think this looks like a useful integration and I'm sure this will also help others!

I don't think there's much to be done here other than that, so I believe this has been answered and will close this for now. Please come back with more details if you feel there's anything to add and we can always reopen this :+1:
