### ISSUE TITLE
React\Socket\ConnectionException' with message 'mysql server has gone away'

### ISSUE THREAD

**Issue by gobyang** [friends-of-reactphp/mysql#18]
React\Socket\ConnectionException' with message 'mysql server has gone away'

When the code run a long time,It will throw this error.

**Comment by clue** [comment]
This is more or less expected behavior as MySQL defaults to closing the client connection if it is idle for a while. You may use a periodic timer and the `ping()` method to ensure your connection is kept alive.

I hope this helps :+1:
