### ISSUE TITLE
Can we use one connection for more than one query?

### ISSUE THREAD

**Issue by chathu020** [friends-of-reactphp/mysql#23]
I want to query the DB, get the result and then based on result want to query again. can I do this using one connection? After I have used $this->connection->connect(function () {}); do I have to call close method. and please note that my server want to handle large number of queries at once based on the clients it connect.

**Comment by chathu020** [comment]
I want to query the DB, get the result and then based on result want to query again. can I do this using one connection? After I have used $this->connection->connect(function () {}); do I have to call close method. and please note that my server want to handle large number of queries at once based on the clients it connect.

**Comment by clue** [comment]
I wonder what the status is here. @chathu020 have you tried this out and did you run into any issues?

**Comment by CharlotteDunois** [comment]
I am executing more than one query using the same connection and it works fine.

**Comment by clue** [comment]
I'll assume this is resolved and will close this for now, please feel free to report back otherwise :+1:
