### ISSUE TITLE
Can't shift from an empty datastructure  - in case of empty string returned

### ISSUE THREAD

**Issue by DangerLifter** [friends-of-reactphp/mysql#28]
I have a complex case which causes stable "Can't shift from an empty datastructure' exception. Shortest way to repeat situation is below:
```
		$loop = \React\EventLoop\Factory::create();

		$config = array(
				'host'	=> '127.0.0.1',
				'port'		=> '',
				'dbname'	=>'',
				'user'	=> '',
				'passwd'	=> '',
		);

		$mysql = new \React\MySQL\Connection($loop, $config);

		$mysql->connect(function() {});
		$query = 'SELECT \'\' as cnt';
		$mysql->query($query);

		$loop->run();
```

**Comment by clue** [comment]
Thank you for reporting! I can confirm that this library does indeed not return *any* data when it should return the following array: `[['']]`

This seems to only affect empty strings, as using `null`, `0`, `"test"` etc. seems to work just fine.

Any help with this would be much appreciated :+1:
