### ISSUE TITLE
unsafe 'dequeue' in React\MySQL\Protocal\Parser::onError()

### ISSUE THREAD

**Issue by Nuri95** [friends-of-reactphp/mysql#44]
onError method in React\MySQL\Protocal\Parser calls
`$command = $this->queue->dequeue();`
while queue can be empty, resulting in RuntimeException from SplQueue
Example: server has gone away error.
minimum code:
```
<?php
require_once __DIR__ . '/vendor/autoload.php';

$loop = \React\EventLoop\Factory::create();

$config = [
    'host'   => '127.0.0.1',
    'port'   => 3306,
    'dbname' => 'test',
    'user'   => 'test',
    'passwd' => 'test',
];
$mysql = new \React\MySQL\Connection($loop, $config);
$mysql->on('error', function ($e) {
    if ($e instanceof \Throwable) {
        echo 'error event ' . $e->getMessage() . PHP_EOL;
    }
});
$mysql->connect(function ($err) {
    if ($err instanceof \Throwable) {
        echo 'connection error: ' . $err->getMessage() . PHP_EOL;
    }
});
$loop->run();
// then service mysql stop
?>
```
Parser fails with runtime exception and 'error' event never called.
my current workaround is:
```
//in React\MySQL\Protocal\Parser::onError()
//$command = $this->queue->dequeue();
if (!$this->queue->isEmpty()) {
    $command = $this->queue->dequeue();
} else { 
    $command = new QuitCommand($this->executor->getConn());
}
```
this allow to emit 'error' event on dummy QuitCommand.

**Comment by clue** [comment]
Thank you for reporting! I can confirm that this bug could indeed lead to an exception in the protocol parser. I've just filed #52 which ensures that all all pending commands are properly rejected if the connection is closed.

This should be the last fix for the current version. After this, we will start working on #4 which will introduce some sane error handling for consumers of this library.
