### ISSUE TITLE
Something strange with streams

### ISSUE THREAD

**Issue by valVk** [friends-of-reactphp/mysql#58]
Hi, I cannot describe it in details, but after a some time working stream starts output something unusual.

![selection_20180621_a20bc9d](https://user-images.githubusercontent.com/1130626/41714621-9d35bed8-7559-11e8-864d-28f3d4921c98.png)

Version of used library below

```
{
            "name": "react/mysql",
            "version": "dev-master",
            "source": {
                "type": "git",
                "url": "https://github.com/friends-of-reactphp/mysql.git",
                "reference": "967ed259ce4eaf28adfe588c391faf2c8439c74d"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/friends-of-reactphp/mysql/zipball/967ed259ce4eaf28adfe588c391faf2c8439c74d",
                "reference": "967ed259ce4eaf28adfe588c391faf2c8439c74d",
                "shasum": ""
            },
            "require": {
                "evenement/evenement": "^3.0 || ^2.1 || ^1.1",
                "php": ">=5.4.0",
                "react/event-loop": "^1.0 || ^0.5 || ^0.4 || ^0.3",
                "react/socket": "^1.0 || ^0.8"
            },
            "require-dev": {
                "phpunit/phpunit": "^4.8.35"
            },
            "type": "library",
            "autoload": {
                "psr-4": {
                    "React\\MySQL\\": "src"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "description": "Async MySQL database client for ReactPHP.",
            "keywords": [
                "async",
                "database",
                "mysql",
                "reactphp"
            ],
            "time": "2018-06-20T18:40:29+00:00"
        },
```
The same code but for version 0.3.3 is working fine

code sample

```php

$coreResource = $connection->query('SELECT * FROM core_resource');

$coreResource->on('result', function ($result, $command, $conn) {
  if ($command->hasError()) {
    $error = $command->getError();
    echo 'Error: ' . $error->getMessage() . PHP_EOL;
  } else {
    echo 'CORE RESOURCE2 ' . $result['id'] . ' - ' . $result['resource'] . PHP_EOL;
  }
});
```

**Comment by clue** [comment]
@valVk Thank you for reporting!

Unfortunately, I'm currently unable to reproduce the problem you're seeing.

Is the problem you're seeing reproducible? Does this only happen for certain queries, perhaps certain data types or column lengths? Can you send me (an extract of) the data that is causing these issues for you?

**Comment by valVk** [comment]
@clue here you go https://github.com/valVk/mysql-stream-test-env

There is exact snapshot of my dev env.
You can find here 2 approaches `query` and `queryStream` both show identical issue. Branch of react/mysql is dev-master.

**Comment by clue** [comment]
@valVk Thank you for providing the details for your test setup, I can now reproduce this locally and will get back to this ticket as soon as I have any new info! :+1:

**Comment by clue** [comment]
@valVk I've been able to track this down and believe I have found the issue here: https://github.com/friends-of-reactphp/mysql/pull/54/files#diff-2031b03ede17eedd651eae219aa02d8fR88

As a quickfix, you can simply remove the `+ 1` here and everything should be working again. For the record, this only affects the current `master` branch and only affects rather long response messages with at least ~16000 entries which is why this wasn't caught by the current test suite. I will file a PR that addresses the fundamental issue later today :+1:

**Comment by clue** [comment]
See #59 for fix :shipit: :+1:

**Comment by valVk** [comment]
Thanks, looks awesome!
