### ISSUE TITLE
'Too many connections' error is not properly handled

### ISSUE THREAD

**Issue by freedemster** [friends-of-reactphp/mysql#81]
I try to open a fixed number of connections to MySQL and got a weird exception:
```
Call to a member function emit() on null
```

I start to debug code and find out that if we got 'Too many connections' error from MySQL we got NULL here here https://github.com/friends-of-reactphp/mysql/blob/master/src/Io/Parser.php#L281

**Comment by clue** [comment]
@freedemster Thank you for spotting and reporting!

I can confirm that creating an excessive number this connections does indeed raise this error. 

Does anybody feel like picking this up and filing a PR? :+1:

**Comment by clue** [comment]
I've just filed #83 to fix this bug :+1: 

For the reference, here's the script I've used to reproduce the "Too many connections" error:

```php
$loop = React\EventLoop\Factory::create();
$factory = new Factory($loop);

$uri = 'test:test@localhost/test';
$n = isset($argv[1]) ? (int)$argv[1] : 200;

for ($i = 0; $i < $n; ++$i) {
    //create a mysql connection for executing query
    $factory->createConnection($uri)->then(function (ConnectionInterface $connection) use ($i) {
        echo 'Connection ' . $i . ' okay' . PHP_EOL;
        // keep idle connection
    }, function (Exception $error) use ($i) {
        echo 'Connection ' . $i . ' error ' . $error->getCode() . ': ' . $error->getMessage() . PHP_EOL;
    });
}

$loop->run();
```

**Comment by freedemster** [comment]
Thanks!
