### ISSUE TITLE
connect() method does not report errors

### ISSUE THREAD

**Issue by jacobson** [friends-of-reactphp/mysql#9]
```
$dbConnection = new React\MySQL\Connection($loop, array(
'dbname' => 'mydb',
'user'   => '',
'passwd' => '',
));
$dbConnection->connect(function ($err, $conn) use ($loop) {
    echo "abc";
    $this->assertEquals("Access denied for user 'test'@'localhost' (using password: YES)", $err->getMessage());
    $this->assertInstanceOf('React\MySQL\Connection', $conn);
    //$loop->stop();
});
```

Even though connection is rejected we are not notified with the above code. Therefore we have to use the following to catch the error. I don't think that this is the expected behaviour for the above code block. Or is it?

```
$dbConnection->on('error',function($error){echo "$error";});
```

**Comment by dustingraham** [comment]
Looking at the code, you're right. The connect callback is only called on authenticated. And, the error handler is called on error.

**Comment by clue** [comment]
The current code should correctly notify you through the callback when the remote server rejects your authentication information (such as invalid username/password). This is also covered by the test suite.

However, the current code does not notify you through the callback if the underlying TCP/IP connection to the server is rejected (such as invalid hostname / port). However, it does notify you through the `error` event.

I agree that this inconsistency is rather annoying and should be fixed. I'll look into this :+1:
