### ISSUE TITLE
LazyConnection failed to use password with special characters

### ISSUE THREAD

**Issue by BragaDevOps** [friends-of-reactphp/mysql#95]
I had problems with LazyConnection regarding password with special characters that broke with the parse_url function, for example:

$uri = "dbuser:xpto123?otpx$xpo88#>@127.0.0.1:3306/dbname?idle=20.0&timeout=-1";

In the LazyConnection.php class constructor, at line 37, the parse_url function will break the URI in the wrong way because of the "?" Character.

In a palliative solution, when I pass the password I used the function rawurlencode() and in the constructor of the AuthenticateCommand class, I made the following adaptation:

Line 23: $this->passwd = addslashes(rawurldecode($passwd));

Could they solve this problem for good?

**Comment by clue** [comment]
@BragaDevOps That's a good question!

I don't think this is currently covered by the documentation, but if your credentials contain special characters, you can simply pass them in percent-encoded like this:

```php
$user = 'n@me';
$pass = '$3cr37';
$host = 'localhost';
$db = 'test';

$uri = rawurlencode($user) . ':' . rawurlencode($pass) . '@' . $host . '/' . rawurlencode($db);
$connection = $factory->createLazyConnection($uri);
```

I hope this helps :+1: 

Also, we should totally add this to the documentation. Does anybody feel like filing a PR? :shipit:
