### ISSUE TITLE
Error:  Call to a member function emit() on null

### ISSUE THREAD

**Issue by woytam** [friends-of-reactphp/mysql#97]
I have run into similar error like issue #70 caused by calling in [Parser.php#L189](/src/Io/Parser.php#L189) when MySQL is shutdowning. 
```
In Parser.php line 292: Call to a member function emit() on null
```
The last parsed packet is
```
[DEBUG] <React\MySQL\Io\Parser:187> Error Packet:1927 Connection was killed
```
Error packet is sent by MariaDB server, [list of error codes](https://mariadb.com/kb/en/library/mariadb-error-codes/) includes code 1927.
Steps to reproduce:
* Connect to DB, waits to establish connection
* Shutdown MySQL server
* Make Query

When error packet is received, `$this->currCommand` is `null`. 
Trying to call `$this->executor->dequeue()` ends in error `Can't shift from an empty datastructure`.

I cannot figure out, when `$this->currCommand` is set to null.

**Comment by clue** [comment]
@woytam Thanks for reporting!

Unfortunately, I'm currently unable to reproduce the problem you're seeing.

Is the problem you're seeing reproducible? Does this only happen for certain queries, perhaps certain data types or column lengths? Can you send me (an extract of) the data that is causing these issues for you?

In particular, how can we best reproduce "Shutdown MySQL server"? I've tried manually killing the database process and also sending a "kill" for the connection ID, both successfully resulted in a successful "close" event (as expected). Can you verify you're running the latest version?

**Comment by woytam** [comment]
Shutdown is emitted by `systemctl stop mariadb`. It looks like MariaDB fires error before closing the connection, what is different agains killing the process.
I will prepare a gist with use case.

**Comment by woytam** [comment]
I have created a small [gist](https://gist.github.com/woytam/80965fb70300cdf34fafbaef0668a3b8) with use case code.
Run `php index.php` and after connection is established, run command `systemctl restart mariadb`. 
This Uncaught Error is not showing up on Windows, possibly due to problematic handling of signals. On Windows, `$connection` fires `mysql server has gone away` as inteded.
My test environment:
* CentOS 7
* MariaDB 10.1.37
* PHP v7.1.24

**Comment by clue** [comment]
@woytam Thanks for the update! I've just filed https://github.com/friends-of-reactphp/mysql/pull/102 which should fix this issue, can you verify this? :shipit:

**Comment by woytam** [comment]
Thank you @clue, I can confirm that #102 solves this bug.
